# Generated by Django 4.1.4 on 2022-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
