# Generated by Django 4.1.4 on 2023-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(help_text='upload your cv', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='edeucation',
            name='year',
            field=models.IntegerField(),
        ),
    ]
