# Generated by Django 4.1.4 on 2023-02-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_cv_alter_edeucation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.IntegerField(),
        ),
    ]
