# Generated by Django 4.1.4 on 2023-02-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_experience_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edeucation',
            name='last',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='last',
        ),
    ]
